import { Estado } from '../general/Estado';
import { Empresa } from '../general/Empresa';
import { Resolucion } from './Resolucion';
import { Sede } from '../general/Sede';
import { Proyecto } from '../general/Proyecto';
import { SubProyecto } from '../general/SubProyecto';
import { Tercero } from '../general/Tercero';
import { Documento } from './Documento';
import { Operacion } from './Operacion';
import { Moneda } from '../general/Moneda';

export class Factura {
    fact_codi: number;
    fact_tipo: string;
    sede_codi: number;
    sedeCodi: Sede;
    proy_codi: number;
    proyCodi: Proyecto;
    spro_codi: number;
    sproCodi: SubProyecto;
    cias_codi: number;
    ciasCodi: Empresa;
    fact_fech: Date;
    reso_codi: number;
    resoCodi: Resolucion;
    reso_pref: string;
    fact_cons: number;
    pers_auxi: number;
    persAuxi: Tercero;
    fact_peri: number;
    fact_venc: Date;
    fact_obse: string;
    esta_codi: string;
    estaCodi: Estado;
    usu_logi: number;
    temp_codi: number;
    oper_codi: number;
    docu_codi: number;
    mone_codi: number;
    fact_tcam: number;
    docuCodi: Documento;
    operCodi: Operacion;
    moneCodi: Moneda;
}